# Generated by Django 2.1.5 on 2019-01-28 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_statement_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='pub_date',
        ),
    ]
